import { useEffect, useState } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { Download, FileJson, FileText, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { usePolicyLabStore } from '@/lib/store';
import { permissivePolicy, restrictivePolicy } from '@/lib/data/policies';
import { AnimatedBackground } from '@/components/effects';

export default function Export() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const scenarioId = searchParams.get('scenario');
  
  const { selectedScenario, diff, loadScenarioData } = usePolicyLabStore();
  const [downloadedItems, setDownloadedItems] = useState<Set<string>>(new Set());
  
  useEffect(() => {
    if (!scenarioId) {
      navigate('/scenarios');
      return;
    }
    if (!selectedScenario || selectedScenario.id !== scenarioId) {
      loadScenarioData(scenarioId);
    }
  }, [scenarioId, selectedScenario, loadScenarioData, navigate]);
  
  if (!selectedScenario || !diff) return null;
  
  const downloadJSON = (data: object, filename: string, itemKey: string) => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setDownloadedItems(prev => new Set(prev).add(itemKey));
  };
  
  const downloadMarkdown = (content: string, filename: string, itemKey: string) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setDownloadedItems(prev => new Set(prev).add(itemKey));
  };
  
  const generateRunReport = () => {
    return `# Run Report: ${selectedScenario.name}

## Scenario Details
- **ID**: ${selectedScenario.id}
- **Category**: ${selectedScenario.category}
- **Risk Level**: ${selectedScenario.risk_level}
- **Spec Version**: v0.1

## Description
${selectedScenario.description}

## Event Stream
${selectedScenario.event_stream.map((e, i) => `
### Event ${i + 1}: ${e.type.toUpperCase()}
${e.narrative}
${e.details ? `\n> ${e.details}` : ''}
`).join('\n')}

---
*Generated by POLICYLAB v0.1*
`;
  };
  
  const generateDiffReport = () => {
    const divergence = diff.divergence_points[0];
    return `# Diff Report: ${selectedScenario.name}

## Policies Compared
- **Policy A**: ${permissivePolicy.name} (${permissivePolicy.hash})
- **Policy B**: ${restrictivePolicy.name} (${restrictivePolicy.hash})

## Divergence Point
${divergence.event_narrative}

### Policy A Decision: ${divergence.policy_a_decision.decision}
- **Reason Codes**: ${divergence.policy_a_decision.reason_codes.join(', ')}
- **Narrative**: ${divergence.policy_a_decision.narrative}

### Policy B Decision: ${divergence.policy_b_decision.decision}
- **Reason Codes**: ${divergence.policy_b_decision.reason_codes.join(', ')}
- **Narrative**: ${divergence.policy_b_decision.narrative}

## Consequence Summary

### What Happened
${diff.consequence_summary.what_happened}

### What Was Prevented
${diff.consequence_summary.what_was_prevented}

### Tradeoff
${diff.consequence_summary.tradeoff}

## Metrics
| Metric | Value |
|--------|-------|
| Spend Exposure Delta | ${diff.consequence_summary.metrics.spend_exposure_delta} |
| Human Escalations | ${diff.consequence_summary.metrics.human_escalation_count} |
| Autonomy Change | ${diff.consequence_summary.metrics.autonomy_change} |
| Risk Avoided | ${diff.consequence_summary.metrics.risk_avoided} |

---
*Generated by POLICYLAB v0.1*
*Scenario ID: ${selectedScenario.id}*
*Policy Hashes: ${permissivePolicy.hash}, ${restrictivePolicy.hash}*
`;
  };

  return (
    <div className="min-h-screen pt-28 pb-20 px-6 relative overflow-hidden">
      <AnimatedBackground variant="subtle" />
      
      <div className="max-w-4xl mx-auto relative z-10">
        {/* Header */}
        <header className="mb-16 animate-fade-in">
          <h1 className="text-4xl md:text-5xl font-medium">Export Results</h1>
          <p className="text-lg text-muted-foreground mt-4">
            Download policy definitions and reports for <span className="text-foreground">{selectedScenario.name}</span>
          </p>
        </header>
        
        {/* Export options */}
        <div className="space-y-4">
          {/* Policy A JSON */}
          <ExportCard
            icon={<FileJson className="h-5 w-5" />}
            title="Policy A: Permissive Standard"
            description="Full policy definition including constraints and raw JSON"
            format="JSON"
            downloaded={downloadedItems.has('policy-a')}
            onDownload={() => downloadJSON(
              { ...permissivePolicy, scenario_id: selectedScenario.id, spec_version: 'v0.1' },
              `policy-permissive-${permissivePolicy.hash}.json`,
              'policy-a'
            )}
          />
          
          {/* Policy B JSON */}
          <ExportCard
            icon={<FileJson className="h-5 w-5" />}
            title="Policy B: Restrictive Standard"
            description="Full policy definition including constraints and raw JSON"
            format="JSON"
            downloaded={downloadedItems.has('policy-b')}
            onDownload={() => downloadJSON(
              { ...restrictivePolicy, scenario_id: selectedScenario.id, spec_version: 'v0.1' },
              `policy-restrictive-${restrictivePolicy.hash}.json`,
              'policy-b'
            )}
          />
          
          {/* Run Report */}
          <ExportCard
            icon={<FileText className="h-5 w-5" />}
            title="Run Report"
            description="Complete scenario timeline with all events"
            format="Markdown"
            downloaded={downloadedItems.has('run-report')}
            onDownload={() => downloadMarkdown(
              generateRunReport(),
              `run-report-${selectedScenario.id}.md`,
              'run-report'
            )}
          />
          
          {/* Diff Report */}
          <ExportCard
            icon={<FileText className="h-5 w-5" />}
            title="Diff Report"
            description="Policy comparison with divergence analysis and metrics"
            format="Markdown"
            downloaded={downloadedItems.has('diff-report')}
            onDownload={() => downloadMarkdown(
              generateDiffReport(),
              `diff-report-${selectedScenario.id}.md`,
              'diff-report'
            )}
          />
        </div>
        
        {/* Metadata */}
        <div className="mt-12 p-4 rounded-lg bg-muted/30 border border-border">
          <p className="text-xs font-mono text-muted-foreground">
            All exports stamped with:
          </p>
          <div className="mt-2 flex flex-wrap gap-4 text-xs font-mono">
            <span>Scenario: {selectedScenario.id}</span>
            <span>Policy A: {permissivePolicy.hash}</span>
            <span>Policy B: {restrictivePolicy.hash}</span>
            <span>Spec: v0.1</span>
          </div>
        </div>
      </div>
    </div>
  );
}

interface ExportCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  format: string;
  downloaded: boolean;
  onDownload: () => void;
}

function ExportCard({ icon, title, description, format, downloaded, onDownload }: ExportCardProps) {
  return (
    <div className="flex items-center justify-between p-4 rounded-lg border border-border bg-card animate-fade-in">
      <div className="flex items-start gap-4">
        <div className="p-2 rounded bg-muted/50 text-muted-foreground">
          {icon}
        </div>
        <div>
          <h3 className="font-medium">{title}</h3>
          <p className="text-sm text-muted-foreground">{description}</p>
        </div>
      </div>
      <div className="flex items-center gap-3">
        <span className="text-xs font-mono text-muted-foreground">{format}</span>
        <Button
          variant={downloaded ? "outline" : "default"}
          size="sm"
          onClick={onDownload}
          className="min-w-[100px]"
        >
          {downloaded ? (
            <>
              <Check className="mr-2 h-4 w-4" />
              Downloaded
            </>
          ) : (
            <>
              <Download className="mr-2 h-4 w-4" />
              Download
            </>
          )}
        </Button>
      </div>
    </div>
  );
}
